### ISSUE TITLE
Bad Rendering on my pixel 7

### ISSUE THREAD

**Issue by gilluc** [rishikanthc/markopolis#1]
![Screenshot_20240814-155030](https://github.com/user-attachments/assets/1a504f7f-5e4c-4381-a371-f7cbe2a292c2)
I like the idea behind your app....

**Comment by rishikanthc** [comment]
Sorry about this. Right now, the site isn't optimized for mobile yet. I'm working on it now. Will fix and push out an update some time today.

**Comment by rishikanthc** [comment]
It has been fixed in the latest release (0.1.7). Pushed the package and have updated the docker image. let me know if you still see this issue.

**Comment by gilluc** [comment]
The bad rendering was on your docs pages and I see it fixed now!
Great job.
Gilles


Le 14 août 2024 16:56:47 GMT+02:00, Rishikanth Chandrasekaran ***@***.***> a écrit :
