### ISSUE TITLE
sticky side "menu" / navigation bar on demo site

### ISSUE THREAD

**Issue by cromelex** [rishikanthc/markopolis#10]
(first of all, congrats on the new release. Based on the changelog I think you're getting this to a solid core stage, where it can fulfill the stated original goal - a free replacement for Obsidian Publish, and an easy way to get a basic site up from .md files).

I've only just checked the demo site (post update) and I'm seeing a behaviour of mobile (on Firefox 129.0.2 on a Pixel 7) where the side menu is sticky. Clicking on a link doesn't dismiss the "menu" as it should. I even waited a bit longer to see if it was some sort of delay but no, only dismisses when I click on the main view.

Video below:

https://github.com/user-attachments/assets/91895d2d-a39f-499e-8593-4f734427bb4c

**Comment by rishikanthc** [comment]
Thank you for your words of encouragement :) Your feedback has been extremely valuable throughout this process.
Ahhh I think I know what the issue is. Will upload a fix in a bit today. This is an easy fix.

**Comment by rishikanthc** [comment]
Check out the new release. this should be solved now :)
