### ISSUE TITLE
Error when trying to build Dockerimage - Caddyfile not found

### ISSUE THREAD

**Issue by Redthirst** [rishikanthc/markopolis#11]
Simply put, when I'm trying to build the Docker image, it's throwing an error when it tries to copy the Caddyfile.

`[+] Building 0.9s (14/15)                                                                          docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2.12kB                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.11-slim-bookworm                                       0.6s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 3.63kB                                                                                0.0s
 => CANCELED [ 1/11] FROM docker.io/library/python:3.11-slim-bookworm@sha256:ad5dadd957a398226996bc4846e522c39f2a  0.1s
 => => resolve docker.io/library/python:3.11-slim-bookworm@sha256:ad5dadd957a398226996bc4846e522c39f2a77340b531b2  0.0s
 => => sha256:ad5dadd957a398226996bc4846e522c39f2a77340b531b28aaab85b2d361210b 9.12kB / 9.12kB                     0.0s
 => => sha256:3b6efc048405b61ba4baa60f7ccb1f8e131e8ce4ca3b6ebb5108084f68c86c4d 1.94kB / 1.94kB                     0.0s
 => => sha256:10f461201cdbe84a59218caa9976c7a294128bef510ddb598cec9f50b5e55f04 6.89kB / 6.89kB                     0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 3.54kB                                                                                0.0s
 => CACHED [ 2/11] RUN apt-get update &&     apt-get install -y --no-install-recommends     nodejs     npm     gi  0.0s
 => CACHED [ 3/11] RUN python -m venv /opt/venv                                                                    0.0s
 => CACHED [ 4/11] RUN /bin/sh -c ". /opt/venv/bin/activate &&     pip install --upgrade pip &&     pip install -  0.0s
 => CACHED [ 5/11] WORKDIR /app/frontend                                                                           0.0s
 => CACHED [ 6/11] COPY frontend/package*.json ./                                                                  0.0s
 => CACHED [ 7/11] RUN npm ci                                                                                      0.0s
 => CACHED [ 8/11] COPY frontend/ ./                                                                               0.0s
 => CACHED [ 9/11] RUN npm run build                                                                               0.0s
 => ERROR [10/11] COPY Caddyfile /etc/caddy/Caddyfile                                                              0.0s
------
 > [10/11] COPY Caddyfile /etc/caddy/Caddyfile:
------

 4 warnings found (use docker --debug to expand):
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "MARKOPOLIS_API_KEY") (line 33)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "VITE_MARKOPOLIS_API_KEY") (line 37)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "VITE_MARKOPOLIS_API_KEY") (line 39)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "MARKOPOLIS_API_KEY") (line 41)
Dockerfile:48
--------------------
  46 |
  47 |     # Copy Caddyfile
  48 | >>> COPY Caddyfile /etc/caddy/Caddyfile
  49 |
  50 |     # Expose ports
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 63cd62c7-bca2-4c7f-befd-0151216174c6::ox4lfkk0ikywaf2c9aftoi61y: "/Caddyfile": not found`

**Comment by rishikanthc** [comment]
My bad. Just realized I didn't commit the caddyfile. Will upload in a few mins.

**Comment by rishikanthc** [comment]
Fixed. you should be able to build it now. closing this for now but let me know if you face any issues.
