### ISSUE TITLE
Failed to build Docker image - Filetree.svelte not found

### ISSUE THREAD

**Issue by Redthirst** [rishikanthc/markopolis#12]
After the previous issue with the missing Caddyfile got resolved, I tried to build again and encountered a different issue:

`2.990 [vite:load-fallback] Could not load /app/frontend/src/lib/components/Filetree.svelte (imported by src/routes/+layout.svelte): ENOENT: no such file or directory, open '/app/frontend/src/lib/components/Filetree.svelte'
2.990 Error: Could not load /app/frontend/src/lib/components/Filetree.svelte (imported by src/routes/+layout.svelte): ENOENT: no such file or directory, open '/app/frontend/src/lib/components/Filetree.svelte'`

**Comment by rishikanthc** [comment]
Sorry this was an error with my .gitignore which caused the lib folder to be removed. Just added it. Try again and let me know if it's resolved. I'll leave this open till you confirm.

**Comment by Redthirst** [comment]
It appears to have worked, thanks!
