### ISSUE TITLE
Error running mdsync on the local machine

### ISSUE THREAD

**Issue by Redthirst** [rishikanthc/markopolis#13]
Trying to run mdsync returns 
`ModuleNotFoundError: No module named 'fcntl'`

From what I know, fcntl doesn't work with Windows, so does this mean that Markopolis isn't meant to be used with Windows machines? Or is there a workaround?

**Comment by rishikanthc** [comment]
There's a workaround for this. I can use a different way to read files. I'll need your help testing it on windows though as I don't have a windows machine. Let me make some changes and I'll keep you posted. 
Apologies for the delay. Was held up with some other stuff.

**Comment by Redthirst** [comment]
Right, that makes sense. I've ended up using a different method to achieve what I needed. You can close the issue, but I think you should update the README to make it clear that it's not really meant for Windows machines.

**Comment by rishikanthc** [comment]
Got it. I'll add a caveat. I'll also fix this in a patch.

**Comment by rishikanthc** [comment]
This should be fixed now. You should be able to run it on windows. I couldn't test it unfortunately as I don't have a windows machine. But let me know if this works.
