### ISSUE TITLE
Incorrect volume mapping in github readme

### ISSUE THREAD

**Issue by cromelex** [rishikanthc/markopolis#17]
Currently, the readme says

```
    volumes:
      - ./pb_data:/app/pb
```
This is actually empty. When I changed the container it was losing all the permanent storage. (ie, losing previously uploaded content).

I  checked markopolis.app and it lists a different volume to map:

```
    volumes:
      - markopolis_data:/app/db
```

This seems to work fine and I can now see the content being stored there.

In short, `:/app/pb` needs to be replaced with `:/app/db` in the sample docker compose in the github readme.

**Comment by rishikanthc** [comment]
Got it. I'll change the documentation. Documentation is still a work in progress and might contain small errors like this. Bear with me while I clean up. Appreciate pointing this out as it's so small and I would have missed it.

**Comment by cromelex** [comment]
Documentation is always tricky!
If I spot anything else I'll point it out.
Thanks
