### ISSUE TITLE
[mobile] Text is cut off on right side

### ISSUE THREAD

**Issue by itsthejoker** [rishikanthc/markopolis#2]
Attached is a screenshot showing that text is cut off on the right side. This appears on all pages.

![Screenshot_20240814-160816.png](https://github.com/user-attachments/assets/d4096c27-2769-494b-9416-d0f2001e4773)

Pixel 6 Pro, Firefox 129.0 (Build #2016035991)

**Comment by rishikanthc** [comment]
Fixed in latest release 0.2.0
