### ISSUE TITLE
[mobile] Check boxes are rendering at different sizes

### ISSUE THREAD

**Issue by itsthejoker** [rishikanthc/markopolis#3]
On the Roadmap page, not all the check boxes are rendering as square depending on the length of the line. See attached screenshot.

![Screenshot_20240814-160836.png](https://github.com/user-attachments/assets/ac52fabf-4dec-41d5-affd-37c89933149e)

Pixel 6 Pro, Firefox 129.0 (Build #2016035991)

**Comment by rishikanthc** [comment]
Fixed in latest release 0.2.0
