### ISSUE TITLE
consume command always picks up the same api url

### ISSUE THREAD

**Issue by kausar007** [rishikanthc/markopolis#5]
I am using the docker compose example from readme and running the server. I am also running a python container on the same docker network. I can reach the server from the client container using curl so there is no connectivity issue. However consume command dow not work. It is getting locahost:8000 from default settings and trying to connect to that instead of using the domain from my yaml config file. 

```
[kausar@home]$ consume
ERROR:markopolis.scripts.consume:Unable to connect to the server at http://localhost:8000. Please ensure the server is running.

[kausar@home]$  echo $MARKOPOLIS_CONFIG_PATH
/tmp/config.yaml

[kausar@home]$  cat /tmp/config.yaml
domain: "http://markopolis:8080"
api_key: <omitted>
```

**Comment by rishikanthc** [comment]
That's strange. Gimme a few minutes. I'll debug this right away. Should be easy to solve.

**Comment by rishikanthc** [comment]
I just noticed.. you said you are running a python container on the same network.. Are you running consume from within docker ? The consume command is meant to be run on your local machine where the markdown files are stored. Can you clarify this ?

**Comment by kausar007** [comment]
I am running the consume command from another container (not where markopolis server/ui is running).
you can think of that as my local machine. its a separate container that has access to my markopolis server container.

**Comment by rishikanthc** [comment]
Okay so I identified the issue. The package expects the arguments to be set under default. Here's a sample config.yaml

```yaml
default:
  domain: https://markopolis:8080
  api_key: <redacted>
  title: Markopolis
```

I'll fix this up in a later release. apologies for the inconvenience. Please let me know if this resolves the issue.

**Comment by kausar007** [comment]
Yep. That worked. Thanks

**Comment by cromelex** [comment]
Sorry to hijack but looking into the python package and being a newbie, how exactly do I set the `MARKOPOLIS_CONFIG_PATH` ? 

Also, how yould you setup the local part if I wanted to use 2 separate domains? (The server side is obvious).

**Comment by rishikanthc** [comment]
MARKOPOLIS_CONFIG_PATH needs to be set as an environment variable. It's not specific to Python. The Python package is simply reading the environment variable. 
If you're using bash or zsh you can do this with export MARKOPOLIS_CONFIG_PATH=<path>
This will persist only as long as your session. If you want it to persist beyond that simply add the same line to your ~/.bashrc

I'm not sure what you mean by 2 domains. You only need one domain which is for the server itself. on your local machine you just need to install the package and create a config file like the one shown above. Once you do that you will be able to use the consume command. consume command is an easy way to upload your local markdown files to your server. So just go into the root directory of your md files and run consume. Or you can pass the path of the root directory as a CLI argument to the command. The command will get your api key and server url from the config and upload your md files to the server. 

Hope this clarifies things. Feel free to let me know if you're still not clear. Hope this helps.

**Comment by cromelex** [comment]
> MARKOPOLIS_CONFIG_PATH needs to be set as an environment variable. It's not specific to Python. The Python package is simply reading the environment variable. If you're using bash or zsh you can do this with export MARKOPOLIS_CONFIG_PATH= This will persist only as long as your session. If you want it to persist beyond that simply add the same line to your ~/.bashrc

Cheers this is really helpful. No
No wonder I wasn't finding anything online, I was specifically looking for something python related.

> I'm not sure what you mean by 2 domains. You only need one domain which is for the server itself. on your local machine you just need to install the package and create a config file like the one shown above. Once you do that you will be able to use the consume command. 

I have a lan-only docs.domain.tld to allow people in the house to have easy access to certain bits of info or links which I was storing in a very plain .MD
I _also_ have a public.domain.tld where I wanted to share some notes publicly. 

So basically separate websites.

Looks like I can run 2 containers (one for each) and set a separate config for each. And then I just need to set one or the other config file via the environment variable before consuming via markopolis ( and using the correct paths for each).

**Comment by rishikanthc** [comment]
Yup that would be the way to go for your specific use case. Glad I could help :)
