### ISSUE TITLE
Images not working as expected

### ISSUE THREAD

**Issue by cromelex** [rishikanthc/markopolis#6]
Hi,

Two separate issues linked to images here.

1.  `.wepb` format doesn't seem to be supported, could we get this enhanced? Obsidian Image Converter plugin even uses this as default.
2. standard markdown link for images doesn't seem to work. `![Image alt text](/path/to/img.jpg)`, where the path is relative (ie, within the obsidian vault)
3.  Obsidian flavoured wikilink images work (ie, `![[img.jpg]] works. 

`![[potato.jpg]]` works

`![[potato.webp]]` doesn't work

`![](potato.jpg)` doesn't work

**Comment by rishikanthc** [comment]
This is now fixed. Pull the latest release. All the 3 syntax should work and support for webp has been added as well :)

**Comment by cromelex** [comment]
Works as intended, even when linking from a subfolder. Cheers.

**Comment by cromelex** [comment]
Hi @rishikanthc , I think there was a regression here on 3.0.2.

.webp is no longer working. 

No issue with .jpg etc, nor in loading the .jpg's from a subfolder.

My .webp images are being rendered as links instead ![index-20241024130352442.webp] (https://domain.tld/index-20241024130352442.webp.md)

Thanks
