### ISSUE TITLE
Improvement request - Hide empty folders from "Menu"

### ISSUE THREAD

**Issue by cromelex** [rishikanthc/markopolis#9]
I would like to suggest implementing the ability to hide "empty" folders (ie, not containing .md files) from the navigation menu generated by markopolis.

On the sample website there's a few cases where it currently shows empty folders.

In my own setup, I use an "attachments" folder under which any images or files get stored (from Obsidian). 
Obsidian doesn't support hidden folders so I cannot use a .attachments for example.
I would like this folder not to show up on the bar.

Markopolis is currently generating the image links without issue even when they are stored within the subfolder, so no issues there. 
Example: `![[attachments/home-20240819150659465.webp]]` for an image on home.md. This links and displays fine.

However the navigation menu will now display an empty "attachments" folder.

**Comment by rishikanthc** [comment]
Fixed in v2.0.0 :)
